#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AnswerDatabase")]
	public partial class AnswerAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertChapter(Chapter instance);
    partial void UpdateChapter(Chapter instance);
    partial void DeleteChapter(Chapter instance);
    partial void InsertPage(Page instance);
    partial void UpdatePage(Page instance);
    partial void DeletePage(Page instance);
    partial void InsertQuestion(Question instance);
    partial void UpdateQuestion(Question instance);
    partial void DeleteQuestion(Question instance);
    partial void InsertSection(Section instance);
    partial void UpdateSection(Section instance);
    partial void DeleteSection(Section instance);
    partial void InsertTextbook(Textbook instance);
    partial void UpdateTextbook(Textbook instance);
    partial void DeleteTextbook(Textbook instance);
    partial void InsertUnit(Unit instance);
    partial void UpdateUnit(Unit instance);
    partial void DeleteUnit(Unit instance);
    #endregion
		
		public AnswerAppDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AnswerDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AnswerAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswerAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswerAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswerAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Chapter> Chapters
		{
			get
			{
				return this.GetTable<Chapter>();
			}
		}
		
		public System.Data.Linq.Table<Page> Pages
		{
			get
			{
				return this.GetTable<Page>();
			}
		}
		
		public System.Data.Linq.Table<Question> Questions
		{
			get
			{
				return this.GetTable<Question>();
			}
		}
		
		public System.Data.Linq.Table<Section> Sections
		{
			get
			{
				return this.GetTable<Section>();
			}
		}
		
		public System.Data.Linq.Table<Textbook> Textbooks
		{
			get
			{
				return this.GetTable<Textbook>();
			}
		}
		
		public System.Data.Linq.Table<Unit> Units
		{
			get
			{
				return this.GetTable<Unit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Unique_Id;
		
		private string _UserName;
		
		private string _Email;
		
		private string _Password;
		
		private string _Answers;
		
		private string _MetaData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnique_IdChanging(int value);
    partial void OnUnique_IdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAnswersChanging(string value);
    partial void OnAnswersChanged();
    partial void OnMetaDataChanging(string value);
    partial void OnMetaDataChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unique_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Unique_Id
		{
			get
			{
				return this._Unique_Id;
			}
			set
			{
				if ((this._Unique_Id != value))
				{
					this.OnUnique_IdChanging(value);
					this.SendPropertyChanging();
					this._Unique_Id = value;
					this.SendPropertyChanged("Unique_Id");
					this.OnUnique_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answers", DbType="NVarChar(MAX)")]
		public string Answers
		{
			get
			{
				return this._Answers;
			}
			set
			{
				if ((this._Answers != value))
				{
					this.OnAnswersChanging(value);
					this.SendPropertyChanging();
					this._Answers = value;
					this.SendPropertyChanged("Answers");
					this.OnAnswersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaData", DbType="NVarChar(MAX)")]
		public string MetaData
		{
			get
			{
				return this._MetaData;
			}
			set
			{
				if ((this._MetaData != value))
				{
					this.OnMetaDataChanging(value);
					this.SendPropertyChanging();
					this._MetaData = value;
					this.SendPropertyChanged("MetaData");
					this.OnMetaDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chapter")]
	public partial class Chapter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Chapter_Id;
		
		private string _Chapter_Title;
		
		private System.Nullable<int> _Unit_Id;
		
		private string _Unit_Title;
		
		private System.Nullable<int> _Textbook_Id;
		
		private string _Textbook_Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChapter_IdChanging(int value);
    partial void OnChapter_IdChanged();
    partial void OnChapter_TitleChanging(string value);
    partial void OnChapter_TitleChanged();
    partial void OnUnit_IdChanging(System.Nullable<int> value);
    partial void OnUnit_IdChanged();
    partial void OnUnit_TitleChanging(string value);
    partial void OnUnit_TitleChanged();
    partial void OnTextbook_IdChanging(System.Nullable<int> value);
    partial void OnTextbook_IdChanged();
    partial void OnTextbook_TitleChanging(string value);
    partial void OnTextbook_TitleChanged();
    #endregion
		
		public Chapter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Chapter_Id
		{
			get
			{
				return this._Chapter_Id;
			}
			set
			{
				if ((this._Chapter_Id != value))
				{
					this.OnChapter_IdChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Id = value;
					this.SendPropertyChanged("Chapter_Id");
					this.OnChapter_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Title", DbType="NVarChar(MAX)")]
		public string Chapter_Title
		{
			get
			{
				return this._Chapter_Title;
			}
			set
			{
				if ((this._Chapter_Title != value))
				{
					this.OnChapter_TitleChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Title = value;
					this.SendPropertyChanged("Chapter_Title");
					this.OnChapter_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Id", DbType="Int")]
		public System.Nullable<int> Unit_Id
		{
			get
			{
				return this._Unit_Id;
			}
			set
			{
				if ((this._Unit_Id != value))
				{
					this.OnUnit_IdChanging(value);
					this.SendPropertyChanging();
					this._Unit_Id = value;
					this.SendPropertyChanged("Unit_Id");
					this.OnUnit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Title", DbType="NVarChar(MAX)")]
		public string Unit_Title
		{
			get
			{
				return this._Unit_Title;
			}
			set
			{
				if ((this._Unit_Title != value))
				{
					this.OnUnit_TitleChanging(value);
					this.SendPropertyChanging();
					this._Unit_Title = value;
					this.SendPropertyChanged("Unit_Title");
					this.OnUnit_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Id", DbType="Int")]
		public System.Nullable<int> Textbook_Id
		{
			get
			{
				return this._Textbook_Id;
			}
			set
			{
				if ((this._Textbook_Id != value))
				{
					this.OnTextbook_IdChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Id = value;
					this.SendPropertyChanged("Textbook_Id");
					this.OnTextbook_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Title", DbType="NVarChar(MAX)")]
		public string Textbook_Title
		{
			get
			{
				return this._Textbook_Title;
			}
			set
			{
				if ((this._Textbook_Title != value))
				{
					this.OnTextbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Title = value;
					this.SendPropertyChanged("Textbook_Title");
					this.OnTextbook_TitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Page")]
	public partial class Page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Page_Id;
		
		private string _Page_Number;
		
		private System.Nullable<int> _Section_Id;
		
		private string _Section_Title;
		
		private System.Nullable<int> _Chapter_Id;
		
		private string _Chapter_Title;
		
		private System.Nullable<int> _Unit_Id;
		
		private string _Unit_Title;
		
		private System.Nullable<int> _Textbook_Id;
		
		private string _Textbook_Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPage_IdChanging(int value);
    partial void OnPage_IdChanged();
    partial void OnPage_NumberChanging(string value);
    partial void OnPage_NumberChanged();
    partial void OnSection_IdChanging(System.Nullable<int> value);
    partial void OnSection_IdChanged();
    partial void OnSection_TitleChanging(string value);
    partial void OnSection_TitleChanged();
    partial void OnChapter_IdChanging(System.Nullable<int> value);
    partial void OnChapter_IdChanged();
    partial void OnChapter_TitleChanging(string value);
    partial void OnChapter_TitleChanged();
    partial void OnUnit_IdChanging(System.Nullable<int> value);
    partial void OnUnit_IdChanged();
    partial void OnUnit_TitleChanging(string value);
    partial void OnUnit_TitleChanged();
    partial void OnTextbook_IdChanging(System.Nullable<int> value);
    partial void OnTextbook_IdChanged();
    partial void OnTextbook_TitleChanging(string value);
    partial void OnTextbook_TitleChanged();
    #endregion
		
		public Page()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Page_Id
		{
			get
			{
				return this._Page_Id;
			}
			set
			{
				if ((this._Page_Id != value))
				{
					this.OnPage_IdChanging(value);
					this.SendPropertyChanging();
					this._Page_Id = value;
					this.SendPropertyChanged("Page_Id");
					this.OnPage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page_Number", DbType="NVarChar(MAX)")]
		public string Page_Number
		{
			get
			{
				return this._Page_Number;
			}
			set
			{
				if ((this._Page_Number != value))
				{
					this.OnPage_NumberChanging(value);
					this.SendPropertyChanging();
					this._Page_Number = value;
					this.SendPropertyChanged("Page_Number");
					this.OnPage_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Id", DbType="Int")]
		public System.Nullable<int> Section_Id
		{
			get
			{
				return this._Section_Id;
			}
			set
			{
				if ((this._Section_Id != value))
				{
					this.OnSection_IdChanging(value);
					this.SendPropertyChanging();
					this._Section_Id = value;
					this.SendPropertyChanged("Section_Id");
					this.OnSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Title", DbType="NVarChar(MAX)")]
		public string Section_Title
		{
			get
			{
				return this._Section_Title;
			}
			set
			{
				if ((this._Section_Title != value))
				{
					this.OnSection_TitleChanging(value);
					this.SendPropertyChanging();
					this._Section_Title = value;
					this.SendPropertyChanged("Section_Title");
					this.OnSection_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Id", DbType="Int")]
		public System.Nullable<int> Chapter_Id
		{
			get
			{
				return this._Chapter_Id;
			}
			set
			{
				if ((this._Chapter_Id != value))
				{
					this.OnChapter_IdChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Id = value;
					this.SendPropertyChanged("Chapter_Id");
					this.OnChapter_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Title", DbType="NVarChar(MAX)")]
		public string Chapter_Title
		{
			get
			{
				return this._Chapter_Title;
			}
			set
			{
				if ((this._Chapter_Title != value))
				{
					this.OnChapter_TitleChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Title = value;
					this.SendPropertyChanged("Chapter_Title");
					this.OnChapter_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Id", DbType="Int")]
		public System.Nullable<int> Unit_Id
		{
			get
			{
				return this._Unit_Id;
			}
			set
			{
				if ((this._Unit_Id != value))
				{
					this.OnUnit_IdChanging(value);
					this.SendPropertyChanging();
					this._Unit_Id = value;
					this.SendPropertyChanged("Unit_Id");
					this.OnUnit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Title", DbType="NVarChar(MAX)")]
		public string Unit_Title
		{
			get
			{
				return this._Unit_Title;
			}
			set
			{
				if ((this._Unit_Title != value))
				{
					this.OnUnit_TitleChanging(value);
					this.SendPropertyChanging();
					this._Unit_Title = value;
					this.SendPropertyChanged("Unit_Title");
					this.OnUnit_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Id", DbType="Int")]
		public System.Nullable<int> Textbook_Id
		{
			get
			{
				return this._Textbook_Id;
			}
			set
			{
				if ((this._Textbook_Id != value))
				{
					this.OnTextbook_IdChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Id = value;
					this.SendPropertyChanged("Textbook_Id");
					this.OnTextbook_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Title", DbType="VarChar(MAX)")]
		public string Textbook_Title
		{
			get
			{
				return this._Textbook_Title;
			}
			set
			{
				if ((this._Textbook_Title != value))
				{
					this.OnTextbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Title = value;
					this.SendPropertyChanged("Textbook_Title");
					this.OnTextbook_TitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Question")]
	public partial class Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Question_Id;
		
		private string _Question_Number;
		
		private System.Nullable<int> _Page_Id;
		
		private string _Page_Number;
		
		private System.Nullable<int> _Section_Id;
		
		private string _Section_Title;
		
		private System.Nullable<int> _Chapter_Id;
		
		private string _Chapter_Title;
		
		private System.Nullable<int> _Unit_Id;
		
		private string _Unit_Title;
		
		private System.Nullable<int> _Textbook_Id;
		
		private string _Textbook_Title;
		
		private System.Data.Linq.Binary _Answer;
		
		private System.Data.Linq.Binary _Practice_Problem;
		
		private string _Practice_Problem_Answer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestion_IdChanging(int value);
    partial void OnQuestion_IdChanged();
    partial void OnQuestion_NumberChanging(string value);
    partial void OnQuestion_NumberChanged();
    partial void OnPage_IdChanging(System.Nullable<int> value);
    partial void OnPage_IdChanged();
    partial void OnPage_NumberChanging(string value);
    partial void OnPage_NumberChanged();
    partial void OnSection_IdChanging(System.Nullable<int> value);
    partial void OnSection_IdChanged();
    partial void OnSection_TitleChanging(string value);
    partial void OnSection_TitleChanged();
    partial void OnChapter_IdChanging(System.Nullable<int> value);
    partial void OnChapter_IdChanged();
    partial void OnChapter_TitleChanging(string value);
    partial void OnChapter_TitleChanged();
    partial void OnUnit_IdChanging(System.Nullable<int> value);
    partial void OnUnit_IdChanged();
    partial void OnUnit_TitleChanging(string value);
    partial void OnUnit_TitleChanged();
    partial void OnTextbook_IdChanging(System.Nullable<int> value);
    partial void OnTextbook_IdChanged();
    partial void OnTextbook_TitleChanging(string value);
    partial void OnTextbook_TitleChanged();
    partial void OnAnswerChanging(System.Data.Linq.Binary value);
    partial void OnAnswerChanged();
    partial void OnPractice_ProblemChanging(System.Data.Linq.Binary value);
    partial void OnPractice_ProblemChanged();
    partial void OnPractice_Problem_AnswerChanging(string value);
    partial void OnPractice_Problem_AnswerChanged();
    #endregion
		
		public Question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Question_Id
		{
			get
			{
				return this._Question_Id;
			}
			set
			{
				if ((this._Question_Id != value))
				{
					this.OnQuestion_IdChanging(value);
					this.SendPropertyChanging();
					this._Question_Id = value;
					this.SendPropertyChanged("Question_Id");
					this.OnQuestion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question_Number", DbType="NVarChar(MAX)")]
		public string Question_Number
		{
			get
			{
				return this._Question_Number;
			}
			set
			{
				if ((this._Question_Number != value))
				{
					this.OnQuestion_NumberChanging(value);
					this.SendPropertyChanging();
					this._Question_Number = value;
					this.SendPropertyChanged("Question_Number");
					this.OnQuestion_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page_Id", DbType="Int")]
		public System.Nullable<int> Page_Id
		{
			get
			{
				return this._Page_Id;
			}
			set
			{
				if ((this._Page_Id != value))
				{
					this.OnPage_IdChanging(value);
					this.SendPropertyChanging();
					this._Page_Id = value;
					this.SendPropertyChanged("Page_Id");
					this.OnPage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page_Number", DbType="NVarChar(MAX)")]
		public string Page_Number
		{
			get
			{
				return this._Page_Number;
			}
			set
			{
				if ((this._Page_Number != value))
				{
					this.OnPage_NumberChanging(value);
					this.SendPropertyChanging();
					this._Page_Number = value;
					this.SendPropertyChanged("Page_Number");
					this.OnPage_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Id", DbType="Int")]
		public System.Nullable<int> Section_Id
		{
			get
			{
				return this._Section_Id;
			}
			set
			{
				if ((this._Section_Id != value))
				{
					this.OnSection_IdChanging(value);
					this.SendPropertyChanging();
					this._Section_Id = value;
					this.SendPropertyChanged("Section_Id");
					this.OnSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Title", DbType="NVarChar(MAX)")]
		public string Section_Title
		{
			get
			{
				return this._Section_Title;
			}
			set
			{
				if ((this._Section_Title != value))
				{
					this.OnSection_TitleChanging(value);
					this.SendPropertyChanging();
					this._Section_Title = value;
					this.SendPropertyChanged("Section_Title");
					this.OnSection_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Id", DbType="Int")]
		public System.Nullable<int> Chapter_Id
		{
			get
			{
				return this._Chapter_Id;
			}
			set
			{
				if ((this._Chapter_Id != value))
				{
					this.OnChapter_IdChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Id = value;
					this.SendPropertyChanged("Chapter_Id");
					this.OnChapter_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Title", DbType="NVarChar(MAX)")]
		public string Chapter_Title
		{
			get
			{
				return this._Chapter_Title;
			}
			set
			{
				if ((this._Chapter_Title != value))
				{
					this.OnChapter_TitleChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Title = value;
					this.SendPropertyChanged("Chapter_Title");
					this.OnChapter_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Id", DbType="Int")]
		public System.Nullable<int> Unit_Id
		{
			get
			{
				return this._Unit_Id;
			}
			set
			{
				if ((this._Unit_Id != value))
				{
					this.OnUnit_IdChanging(value);
					this.SendPropertyChanging();
					this._Unit_Id = value;
					this.SendPropertyChanged("Unit_Id");
					this.OnUnit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Title", DbType="NVarChar(MAX)")]
		public string Unit_Title
		{
			get
			{
				return this._Unit_Title;
			}
			set
			{
				if ((this._Unit_Title != value))
				{
					this.OnUnit_TitleChanging(value);
					this.SendPropertyChanging();
					this._Unit_Title = value;
					this.SendPropertyChanged("Unit_Title");
					this.OnUnit_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Id", DbType="Int")]
		public System.Nullable<int> Textbook_Id
		{
			get
			{
				return this._Textbook_Id;
			}
			set
			{
				if ((this._Textbook_Id != value))
				{
					this.OnTextbook_IdChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Id = value;
					this.SendPropertyChanged("Textbook_Id");
					this.OnTextbook_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Title", DbType="NVarChar(MAX)")]
		public string Textbook_Title
		{
			get
			{
				return this._Textbook_Title;
			}
			set
			{
				if ((this._Textbook_Title != value))
				{
					this.OnTextbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Title = value;
					this.SendPropertyChanged("Textbook_Title");
					this.OnTextbook_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Practice_Problem", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Practice_Problem
		{
			get
			{
				return this._Practice_Problem;
			}
			set
			{
				if ((this._Practice_Problem != value))
				{
					this.OnPractice_ProblemChanging(value);
					this.SendPropertyChanging();
					this._Practice_Problem = value;
					this.SendPropertyChanged("Practice_Problem");
					this.OnPractice_ProblemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Practice_Problem_Answer", DbType="NVarChar(50)")]
		public string Practice_Problem_Answer
		{
			get
			{
				return this._Practice_Problem_Answer;
			}
			set
			{
				if ((this._Practice_Problem_Answer != value))
				{
					this.OnPractice_Problem_AnswerChanging(value);
					this.SendPropertyChanging();
					this._Practice_Problem_Answer = value;
					this.SendPropertyChanged("Practice_Problem_Answer");
					this.OnPractice_Problem_AnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Section")]
	public partial class Section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Section_Id;
		
		private string _Section_Title;
		
		private System.Nullable<int> _Chapter_Id;
		
		private string _Chapter_Title;
		
		private System.Nullable<int> _Unit_Id;
		
		private string _Unit_Title;
		
		private System.Nullable<int> _Textbook_Id;
		
		private string _Textbook_Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSection_IdChanging(int value);
    partial void OnSection_IdChanged();
    partial void OnSection_TitleChanging(string value);
    partial void OnSection_TitleChanged();
    partial void OnChapter_IdChanging(System.Nullable<int> value);
    partial void OnChapter_IdChanged();
    partial void OnChapter_TitleChanging(string value);
    partial void OnChapter_TitleChanged();
    partial void OnUnit_IdChanging(System.Nullable<int> value);
    partial void OnUnit_IdChanged();
    partial void OnUnit_TitleChanging(string value);
    partial void OnUnit_TitleChanged();
    partial void OnTextbook_IdChanging(System.Nullable<int> value);
    partial void OnTextbook_IdChanged();
    partial void OnTextbook_TitleChanging(string value);
    partial void OnTextbook_TitleChanged();
    #endregion
		
		public Section()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Section_Id
		{
			get
			{
				return this._Section_Id;
			}
			set
			{
				if ((this._Section_Id != value))
				{
					this.OnSection_IdChanging(value);
					this.SendPropertyChanging();
					this._Section_Id = value;
					this.SendPropertyChanged("Section_Id");
					this.OnSection_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_Title", DbType="NVarChar(MAX)")]
		public string Section_Title
		{
			get
			{
				return this._Section_Title;
			}
			set
			{
				if ((this._Section_Title != value))
				{
					this.OnSection_TitleChanging(value);
					this.SendPropertyChanging();
					this._Section_Title = value;
					this.SendPropertyChanged("Section_Title");
					this.OnSection_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Id", DbType="Int")]
		public System.Nullable<int> Chapter_Id
		{
			get
			{
				return this._Chapter_Id;
			}
			set
			{
				if ((this._Chapter_Id != value))
				{
					this.OnChapter_IdChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Id = value;
					this.SendPropertyChanged("Chapter_Id");
					this.OnChapter_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chapter_Title", DbType="NVarChar(MAX)")]
		public string Chapter_Title
		{
			get
			{
				return this._Chapter_Title;
			}
			set
			{
				if ((this._Chapter_Title != value))
				{
					this.OnChapter_TitleChanging(value);
					this.SendPropertyChanging();
					this._Chapter_Title = value;
					this.SendPropertyChanged("Chapter_Title");
					this.OnChapter_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Id", DbType="Int")]
		public System.Nullable<int> Unit_Id
		{
			get
			{
				return this._Unit_Id;
			}
			set
			{
				if ((this._Unit_Id != value))
				{
					this.OnUnit_IdChanging(value);
					this.SendPropertyChanging();
					this._Unit_Id = value;
					this.SendPropertyChanged("Unit_Id");
					this.OnUnit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Title", DbType="NVarChar(MAX)")]
		public string Unit_Title
		{
			get
			{
				return this._Unit_Title;
			}
			set
			{
				if ((this._Unit_Title != value))
				{
					this.OnUnit_TitleChanging(value);
					this.SendPropertyChanging();
					this._Unit_Title = value;
					this.SendPropertyChanged("Unit_Title");
					this.OnUnit_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Id", DbType="Int")]
		public System.Nullable<int> Textbook_Id
		{
			get
			{
				return this._Textbook_Id;
			}
			set
			{
				if ((this._Textbook_Id != value))
				{
					this.OnTextbook_IdChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Id = value;
					this.SendPropertyChanged("Textbook_Id");
					this.OnTextbook_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Title", DbType="NVarChar(MAX)")]
		public string Textbook_Title
		{
			get
			{
				return this._Textbook_Title;
			}
			set
			{
				if ((this._Textbook_Title != value))
				{
					this.OnTextbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Title = value;
					this.SendPropertyChanged("Textbook_Title");
					this.OnTextbook_TitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Textbook")]
	public partial class Textbook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Unique_Id;
		
		private string _Title;
		
		private string _Edition;
		
		private string _Publisher;
		
		private string _Date_of_Publication;
		
		private System.Nullable<int> _Number_of_Units;
		
		private System.Nullable<int> _Numbe_of_Chapters;
		
		private System.Nullable<int> _Number_of_Sections;
		
		private System.Nullable<int> _Number_of_Pages;
		
		private System.Nullable<int> _Number_of_Questions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnique_IdChanging(int value);
    partial void OnUnique_IdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnEditionChanging(string value);
    partial void OnEditionChanged();
    partial void OnPublisherChanging(string value);
    partial void OnPublisherChanged();
    partial void OnDate_of_PublicationChanging(string value);
    partial void OnDate_of_PublicationChanged();
    partial void OnNumber_of_UnitsChanging(System.Nullable<int> value);
    partial void OnNumber_of_UnitsChanged();
    partial void OnNumbe_of_ChaptersChanging(System.Nullable<int> value);
    partial void OnNumbe_of_ChaptersChanged();
    partial void OnNumber_of_SectionsChanging(System.Nullable<int> value);
    partial void OnNumber_of_SectionsChanged();
    partial void OnNumber_of_PagesChanging(System.Nullable<int> value);
    partial void OnNumber_of_PagesChanged();
    partial void OnNumber_of_QuestionsChanging(System.Nullable<int> value);
    partial void OnNumber_of_QuestionsChanged();
    #endregion
		
		public Textbook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unique_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Unique_Id
		{
			get
			{
				return this._Unique_Id;
			}
			set
			{
				if ((this._Unique_Id != value))
				{
					this.OnUnique_IdChanging(value);
					this.SendPropertyChanging();
					this._Unique_Id = value;
					this.SendPropertyChanged("Unique_Id");
					this.OnUnique_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edition", DbType="NVarChar(MAX)")]
		public string Edition
		{
			get
			{
				return this._Edition;
			}
			set
			{
				if ((this._Edition != value))
				{
					this.OnEditionChanging(value);
					this.SendPropertyChanging();
					this._Edition = value;
					this.SendPropertyChanged("Edition");
					this.OnEditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="NVarChar(MAX)")]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this.OnPublisherChanging(value);
					this.SendPropertyChanging();
					this._Publisher = value;
					this.SendPropertyChanged("Publisher");
					this.OnPublisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_of_Publication", DbType="NVarChar(MAX)")]
		public string Date_of_Publication
		{
			get
			{
				return this._Date_of_Publication;
			}
			set
			{
				if ((this._Date_of_Publication != value))
				{
					this.OnDate_of_PublicationChanging(value);
					this.SendPropertyChanging();
					this._Date_of_Publication = value;
					this.SendPropertyChanged("Date_of_Publication");
					this.OnDate_of_PublicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_of_Units", DbType="Int")]
		public System.Nullable<int> Number_of_Units
		{
			get
			{
				return this._Number_of_Units;
			}
			set
			{
				if ((this._Number_of_Units != value))
				{
					this.OnNumber_of_UnitsChanging(value);
					this.SendPropertyChanging();
					this._Number_of_Units = value;
					this.SendPropertyChanged("Number_of_Units");
					this.OnNumber_of_UnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numbe_of_Chapters", DbType="Int")]
		public System.Nullable<int> Numbe_of_Chapters
		{
			get
			{
				return this._Numbe_of_Chapters;
			}
			set
			{
				if ((this._Numbe_of_Chapters != value))
				{
					this.OnNumbe_of_ChaptersChanging(value);
					this.SendPropertyChanging();
					this._Numbe_of_Chapters = value;
					this.SendPropertyChanged("Numbe_of_Chapters");
					this.OnNumbe_of_ChaptersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_of_Sections", DbType="Int")]
		public System.Nullable<int> Number_of_Sections
		{
			get
			{
				return this._Number_of_Sections;
			}
			set
			{
				if ((this._Number_of_Sections != value))
				{
					this.OnNumber_of_SectionsChanging(value);
					this.SendPropertyChanging();
					this._Number_of_Sections = value;
					this.SendPropertyChanged("Number_of_Sections");
					this.OnNumber_of_SectionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_of_Pages", DbType="Int")]
		public System.Nullable<int> Number_of_Pages
		{
			get
			{
				return this._Number_of_Pages;
			}
			set
			{
				if ((this._Number_of_Pages != value))
				{
					this.OnNumber_of_PagesChanging(value);
					this.SendPropertyChanging();
					this._Number_of_Pages = value;
					this.SendPropertyChanged("Number_of_Pages");
					this.OnNumber_of_PagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number_of_Questions", DbType="Int")]
		public System.Nullable<int> Number_of_Questions
		{
			get
			{
				return this._Number_of_Questions;
			}
			set
			{
				if ((this._Number_of_Questions != value))
				{
					this.OnNumber_of_QuestionsChanging(value);
					this.SendPropertyChanging();
					this._Number_of_Questions = value;
					this.SendPropertyChanged("Number_of_Questions");
					this.OnNumber_of_QuestionsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Unit")]
	public partial class Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Unit_Id;
		
		private string _Unit_Title;
		
		private System.Nullable<int> _Textbook_Id;
		
		private string _Textbook_Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUnit_IdChanging(int value);
    partial void OnUnit_IdChanged();
    partial void OnUnit_TitleChanging(string value);
    partial void OnUnit_TitleChanged();
    partial void OnTextbook_IdChanging(System.Nullable<int> value);
    partial void OnTextbook_IdChanged();
    partial void OnTextbook_TitleChanging(string value);
    partial void OnTextbook_TitleChanged();
    #endregion
		
		public Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Unit_Id
		{
			get
			{
				return this._Unit_Id;
			}
			set
			{
				if ((this._Unit_Id != value))
				{
					this.OnUnit_IdChanging(value);
					this.SendPropertyChanging();
					this._Unit_Id = value;
					this.SendPropertyChanged("Unit_Id");
					this.OnUnit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Title", DbType="NVarChar(MAX)")]
		public string Unit_Title
		{
			get
			{
				return this._Unit_Title;
			}
			set
			{
				if ((this._Unit_Title != value))
				{
					this.OnUnit_TitleChanging(value);
					this.SendPropertyChanging();
					this._Unit_Title = value;
					this.SendPropertyChanged("Unit_Title");
					this.OnUnit_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Id", DbType="Int")]
		public System.Nullable<int> Textbook_Id
		{
			get
			{
				return this._Textbook_Id;
			}
			set
			{
				if ((this._Textbook_Id != value))
				{
					this.OnTextbook_IdChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Id = value;
					this.SendPropertyChanged("Textbook_Id");
					this.OnTextbook_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Textbook_Title", DbType="NVarChar(MAX)")]
		public string Textbook_Title
		{
			get
			{
				return this._Textbook_Title;
			}
			set
			{
				if ((this._Textbook_Title != value))
				{
					this.OnTextbook_TitleChanging(value);
					this.SendPropertyChanging();
					this._Textbook_Title = value;
					this.SendPropertyChanged("Textbook_Title");
					this.OnTextbook_TitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
